// <auto-generated />
using System;
using FOSCBot.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FOSCBot.Persistence.Migrations
{
    [DbContext(typeof(FosboDbContext))]
    [Migration("20260306100114_AddMasters")]
    partial class AddMasters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FOSCBot.Common.Persistence.Entities.Master", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AuthenticatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserExternalId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserExternalId")
                        .IsUnique();

                    b.ToTable("Masters");
                });

            modelBuilder.Entity("FOSCBot.Common.Persistence.Entities.PhantomCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("PhantomCommands");
                });

            modelBuilder.Entity("FOSCBot.Common.Persistence.Entities.PhantomCommandChat", b =>
                {
                    b.Property<Guid>("PhantomCommandId")
                        .HasColumnType("uuid");

                    b.Property<long>("ChatExternalId")
                        .HasColumnType("bigint");

                    b.HasKey("PhantomCommandId", "ChatExternalId");

                    b.ToTable("PhantomCommandChats");
                });

            modelBuilder.Entity("Navigator.Extensions.Store.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Navigator.Extensions.Store.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Navigator.Extensions.Store.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FOSCBot.Common.Persistence.Entities.PhantomCommandChat", b =>
                {
                    b.HasOne("FOSCBot.Common.Persistence.Entities.PhantomCommand", "PhantomCommand")
                        .WithMany("Chats")
                        .HasForeignKey("PhantomCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhantomCommand");
                });

            modelBuilder.Entity("Navigator.Extensions.Store.Entities.Conversation", b =>
                {
                    b.HasOne("Navigator.Extensions.Store.Entities.Chat", "Chat")
                        .WithMany("Conversations")
                        .HasForeignKey("ChatId");

                    b.HasOne("Navigator.Extensions.Store.Entities.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FOSCBot.Common.Persistence.Entities.PhantomCommand", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("Navigator.Extensions.Store.Entities.Chat", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("Navigator.Extensions.Store.Entities.User", b =>
                {
                    b.Navigation("Conversations");
                });
#pragma warning restore 612, 618
        }
    }
}
