//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOSCBot.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreLinks {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLinks() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FOSCBot.Core.Resources.CoreLinks", typeof(CoreLinks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Ipad {
            get {
                return ResourceManager.GetString("Ipad", resourceCulture);
            }
        }
        
        internal static string IpadAudio {
            get {
                return ResourceManager.GetString("IpadAudio", resourceCulture);
            }
        }
        
        internal static string Nice {
            get {
                return ResourceManager.GetString("Nice", resourceCulture);
            }
        }
        
        internal static string Nvidia {
            get {
                return ResourceManager.GetString("Nvidia", resourceCulture);
            }
        }
        
        internal static string Orks {
            get {
                return ResourceManager.GetString("Orks", resourceCulture);
            }
        }
        
        internal static string P4hit {
            get {
                return ResourceManager.GetString("P4hit", resourceCulture);
            }
        }
        
        internal static string P4hitFast {
            get {
                return ResourceManager.GetString("P4hitFast", resourceCulture);
            }
        }
        
        internal static string Ree {
            get {
                return ResourceManager.GetString("Ree", resourceCulture);
            }
        }
        
        internal static string Stemen {
            get {
                return ResourceManager.GetString("Stemen", resourceCulture);
            }
        }
        
        internal static string Conke {
            get {
                return ResourceManager.GetString("Conke", resourceCulture);
            }
        }
        
        internal static string Stonks {
            get {
                return ResourceManager.GetString("Stonks", resourceCulture);
            }
        }
        
        internal static string HomeMalo {
            get {
                return ResourceManager.GetString("HomeMalo", resourceCulture);
            }
        }
        
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        internal static string SourceChad {
            get {
                return ResourceManager.GetString("SourceChad", resourceCulture);
            }
        }
        
        internal static string GoAhead {
            get {
                return ResourceManager.GetString("GoAhead", resourceCulture);
            }
        }
        
        internal static string CbtExplanation {
            get {
                return ResourceManager.GetString("CbtExplanation", resourceCulture);
            }
        }
        
        internal static string NFT {
            get {
                return ResourceManager.GetString("NFT", resourceCulture);
            }
        }
        
        internal static string NFToad {
            get {
                return ResourceManager.GetString("NFToad", resourceCulture);
            }
        }
        
        internal static string NFTractor {
            get {
                return ResourceManager.GetString("NFTractor", resourceCulture);
            }
        }
        
        internal static string NFTattoo {
            get {
                return ResourceManager.GetString("NFTattoo", resourceCulture);
            }
        }
        
        internal static string NFTu {
            get {
                return ResourceManager.GetString("NFTu", resourceCulture);
            }
        }
        
        internal static string MegatronCbtExperience {
            get {
                return ResourceManager.GetString("MegatronCbtExperience", resourceCulture);
            }
        }
        
        internal static string MegatronCbtImmediate {
            get {
                return ResourceManager.GetString("MegatronCbtImmediate", resourceCulture);
            }
        }
        
        internal static string MuchoTexto {
            get {
                return ResourceManager.GetString("MuchoTexto", resourceCulture);
            }
        }
    }
}
