//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOSCBot.Core.Resources {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreLinks {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLinks() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FOSCBot.Core.Resources.CoreLinks", typeof(CoreLinks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Ipad {
            get {
                return ResourceManager.GetString("Ipad", resourceCulture);
            }
        }
        
        internal static string IpadAudio {
            get {
                return ResourceManager.GetString("IpadAudio", resourceCulture);
            }
        }
        
        internal static string P4hit {
            get {
                return ResourceManager.GetString("P4hit", resourceCulture);
            }
        }
        
        internal static string P4hitFast {
            get {
                return ResourceManager.GetString("P4hitFast", resourceCulture);
            }
        }
        
        internal static string Conke {
            get {
                return ResourceManager.GetString("Conke", resourceCulture);
            }
        }
        
        internal static string HomeMalo {
            get {
                return ResourceManager.GetString("HomeMalo", resourceCulture);
            }
        }
        
        internal static string MuchoTexto {
            get {
                return ResourceManager.GetString("MuchoTexto", resourceCulture);
            }
        }
    }
}
