//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOSCBot.Core.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOSCBot.Core.Domain.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info about FOSC at [fosc.space](https://fosc.space).
        ///Check out my source code at [foscbot](https://github.com/elementh/foscbot).
        ///
        ///Made with ❤️ and gratitude by [Lucas Maximiliano Marino](https://lucasmarino.me) for all the cool people at [FOSC](https://fosc.space). .
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAIqAioDASIAAhEBAxEB/8QAHQAAAAcBAQEAAAAAAAAAAAAAAAIDBAUGBwgBCf/EAGcQAAEDAQQEBgkLDgoIBAYDAAMAAgQFAQYSEwcUIzMRIjEyQkMIFSEkUlNicoI0QVFhY3GBkZKx0RYlNTdEVHN0dZOhorPBCRcYJjY4VpSy8CdVZIOVwtLhhaPT4ihFRmWE8lfD8f/EABsBAAMBAQEBAQAAAAAAAAAAAAACAwQFBgEH/8QAKxEBAQACAgICAAUEAwEBAAAAAAIDEgQiEzIBBREUIzNCMUFRUhUh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HeyBroImage {
            get {
                return ResourceManager.GetString("HeyBroImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T2dnUwACAAAAAAAAAABO8jPpAAAAAFNMI0wBE09wdXNIZWFkAQE4AYC7AAAAAABPZ2dTAAAAAAAAAAAAAE7yM+kBAAAAdgKVyAE2T3B1c1RhZ3MNAAAATGF2ZjU4LjI5LjEwMAEAAAAVAAAAZW5jb2Rlcj1MYXZmNTguMjkuMTAwT2dnUwAAgLsAAAAAAABO8jPpAgAAAGpRsR05AwMDAwMDAwMDAwMDAwMDAwMDAwP/EISFhoiChoOGg4OE/zKH/0bVhv9FfPf/D/8D28/p/wO/ftLt+P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++P/++Im/DbZFbEj6LlG0G/XmQCICIBJKKAGdCO2QcRKD+eZqaLkqLlYCAJlyeIVAkAFuv0jeJIONH5wtIH+4b5HDKNpS1bKK8dtT7oDaxdEZDiChM65UnCl4hPN/TXur/odWLtNpAQA7Wo0o3tbSEFeS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IpadAudio {
            get {
                return ResourceManager.GetString("IpadAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAFNAeoDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NginxImage {
            get {
                return ResourceManager.GetString("NginxImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there _newbie_. What is *FOSC*?
        ///
        ///FOSC stands for `Free Open Source Club`. We are a student association focused on expanding free software and hacker culture..
        /// </summary>
        public static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
    }
}
