//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOSCBot.Core.Domain.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreLinks {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLinks() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FOSCBot.Core.Domain.Resources.CoreLinks", typeof(CoreLinks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        public static string Ipad {
            get {
                return ResourceManager.GetString("Ipad", resourceCulture);
            }
        }
        
        public static string IpadAudio {
            get {
                return ResourceManager.GetString("IpadAudio", resourceCulture);
            }
        }
        
        public static string Nice {
            get {
                return ResourceManager.GetString("Nice", resourceCulture);
            }
        }
        
        public static string Nope {
            get {
                return ResourceManager.GetString("Nope", resourceCulture);
            }
        }
        
        public static string Nvidia {
            get {
                return ResourceManager.GetString("Nvidia", resourceCulture);
            }
        }
        
        public static string Orks {
            get {
                return ResourceManager.GetString("Orks", resourceCulture);
            }
        }
        
        public static string P4hit {
            get {
                return ResourceManager.GetString("P4hit", resourceCulture);
            }
        }
        
        public static string P4hitFast {
            get {
                return ResourceManager.GetString("P4hitFast", resourceCulture);
            }
        }
        
        public static string Ree {
            get {
                return ResourceManager.GetString("Ree", resourceCulture);
            }
        }
        
        public static string Stemen {
            get {
                return ResourceManager.GetString("Stemen", resourceCulture);
            }
        }
        
        public static string Succ {
            get {
                return ResourceManager.GetString("Succ", resourceCulture);
            }
        }
        
        public static string SuccWithTeeth {
            get {
                return ResourceManager.GetString("SuccWithTeeth", resourceCulture);
            }
        }
    }
}
